/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    returnUrl?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    code?: string;
                    state?: string;
                    error?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/lastfm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Configure or validate a Last.fm username
         * @description Validates the provided Last.fm username and stores the configuration in the user session.
         */
        post: operations["ConfigureLastfm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/discogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Configure or validate a Discogs profile
         * @description Validates a Discogs username or collection and stores the configuration in the user session.
         */
        post: operations["ConfigureDiscogs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/setlistfm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Configure or validate a Setlist.fm username or ID
         * @description Validates the provided Setlist.fm identity and stores the configuration in the user session.
         */
        post: operations["ConfigureSetlistFm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/api/match/spotify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Match normalized tracks to Spotify
         * @description Attempts to find Spotify matches for normalized tracks using exact, normalized, fuzzy, and album-based matching strategies.
         */
        post: operations["MatchTracksToSpotify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/api/match/spotify/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Spotify for tracks
         * @description Searches Spotify for tracks matching the given query. Returns up to 5 results.
         */
        get: operations["SearchSpotifyTracks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlist/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a playlist on Spotify
         * @description Creates a new Spotify playlist with the provided tracks. Requires an authenticated session.
         */
        post: operations["CreatePlaylist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/lastfm/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fetch Last.fm data with filters
         * @description Fetches tracks, albums, or artists from a user's Last.fm profile with optional filtering (time period, max results, custom date ranges).
         */
        post: operations["FetchLastfmData"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/lastfm/data/normalized": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fetch normalized Last.fm data
         * @description Fetches Last.fm data and normalizes it to a canonical format for consistent matching across all data sources.
         */
        post: operations["FetchLastfmDataNormalized"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            code: string;
            message: string;
            details?: null | string;
        };
        ConfigureDiscogsRequest: {
            usernameOrCollectionId: string;
        };
        ConfigureDiscogsResponse: {
            username: string;
            collectionUrl: string;
            /** Format: int32 */
            releaseCount: number | string;
            isConfigured: boolean;
        };
        ConfigureLastfmRequest: {
            username: string;
        };
        ConfigureLastfmResponse: {
            username: string;
            /** Format: int32 */
            playCount: number | string;
            profileUrl: string;
            isConfigured: boolean;
        };
        ConfigureSetlistRequest: {
            usernameOrId: string;
        };
        ConfigureSetlistResponse: {
            userId: string;
            displayName: string;
            profileUrl?: null | string;
            /** Format: int32 */
            attendedConcerts?: number | string;
            isConfigured: boolean;
        };
        FetchLastfmDataRequest: {
            username: string;
            filter: components["schemas"]["LastfmFilter"];
        };
        LastfmAlbum: {
            name: string;
            artist: string;
            /** Format: int32 */
            playCount?: number | string;
        };
        LastfmArtist: {
            name: string;
            /** Format: int32 */
            playCount?: number | string;
        };
        LastfmDataResponse: {
            dataType: components["schemas"]["LastfmDataType"];
            tracks: components["schemas"]["LastfmTrack"][];
            albums: components["schemas"]["LastfmAlbum"][];
            artists: components["schemas"]["LastfmArtist"][];
            /** Format: int32 */
            totalResults?: number | string;
        };
        /** @enum {unknown} */
        LastfmDataType: "Tracks" | "Albums" | "Artists";
        LastfmFilter: {
            dataType: components["schemas"]["LastfmDataType"];
            timePeriod: components["schemas"]["LastfmTimePeriod"];
            customStartDate?: null | string;
            customEndDate?: null | string;
            /** Format: int32 */
            maxResults?: number | string;
        };
        /** @enum {unknown} */
        LastfmTimePeriod: "Last7Days" | "Last1Month" | "Last3Months" | "Last6Months" | "Last12Months" | "Overall" | "Custom";
        LastfmTrack: {
            name: string;
            artist: string;
            album?: null | string;
            /** Format: int32 */
            playCount?: number | string;
        };
        MatchedDataResponse: {
            tracks: components["schemas"]["MatchedTrack"][];
            /** Format: int32 */
            totalTracks?: number | string;
            /** Format: int32 */
            matchedCount?: number | string;
            /** Format: int32 */
            unmatchedCount?: number | string;
        };
        MatchedTrack: {
            sourceTrack: components["schemas"]["NormalizedTrack"];
            match?: null | components["schemas"]["SpotifyMatch"];
            isMatched?: boolean;
        };
        /** @enum {unknown} */
        MatchMethod: "Exact" | "Normalized" | "Fuzzy" | "AlbumBased";
        MatchTracksRequest: {
            tracks: components["schemas"]["NormalizedTrack"][];
        };
        NormalizedAlbum: {
            name: string;
            artist: string;
            tracks: components["schemas"]["NormalizedTrack"][];
            sourceMetadata: Record<string, never>;
            source: string;
        };
        NormalizedArtist: {
            name: string;
            sourceMetadata: Record<string, never>;
            source: string;
        };
        NormalizedDataResponse: {
            dataType: string;
            tracks: components["schemas"]["NormalizedTrack"][];
            albums: components["schemas"]["NormalizedAlbum"][];
            artists: components["schemas"]["NormalizedArtist"][];
            /** Format: int32 */
            totalResults?: number | string;
            source: string;
        };
        NormalizedTrack: {
            name: string;
            artist: string;
            album?: null | string;
            sourceMetadata: Record<string, never>;
            source: string;
        };
        PlaylistCreationRequest: {
            name: string;
            description?: null | string;
            isPublic: boolean;
            trackUris: string[];
        };
        PlaylistCreationResponse: {
            playlistId: string;
            uri: string;
            url: string;
            /** Format: int32 */
            tracksAdded: number | string;
        };
        SpotifyMatch: {
            spotifyId: string;
            name: string;
            artist: string;
            album?: null | string;
            uri: string;
            /** Format: int32 */
            confidence: number | string;
            method: components["schemas"]["MatchMethod"];
        };
        SpotifyTrack: {
            id: string;
            name: string;
            artist: string;
            album?: null | string;
            uri: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type ApiError = components['schemas']['ApiError'];
export type ConfigureDiscogsRequest = components['schemas']['ConfigureDiscogsRequest'];
export type ConfigureDiscogsResponse = components['schemas']['ConfigureDiscogsResponse'];
export type ConfigureLastfmRequest = components['schemas']['ConfigureLastfmRequest'];
export type ConfigureLastfmResponse = components['schemas']['ConfigureLastfmResponse'];
export type ConfigureSetlistRequest = components['schemas']['ConfigureSetlistRequest'];
export type ConfigureSetlistResponse = components['schemas']['ConfigureSetlistResponse'];
export type FetchLastfmDataRequest = components['schemas']['FetchLastfmDataRequest'];
export type LastfmAlbum = components['schemas']['LastfmAlbum'];
export type LastfmArtist = components['schemas']['LastfmArtist'];
export type LastfmDataResponse = components['schemas']['LastfmDataResponse'];
export type LastfmDataType = components['schemas']['LastfmDataType'];
export type LastfmFilter = components['schemas']['LastfmFilter'];
export type LastfmTimePeriod = components['schemas']['LastfmTimePeriod'];
export type LastfmTrack = components['schemas']['LastfmTrack'];
export type MatchedDataResponse = components['schemas']['MatchedDataResponse'];
export type MatchedTrack = components['schemas']['MatchedTrack'];
export type MatchMethod = components['schemas']['MatchMethod'];
export type MatchTracksRequest = components['schemas']['MatchTracksRequest'];
export type NormalizedAlbum = components['schemas']['NormalizedAlbum'];
export type NormalizedArtist = components['schemas']['NormalizedArtist'];
export type NormalizedDataResponse = components['schemas']['NormalizedDataResponse'];
export type NormalizedTrack = components['schemas']['NormalizedTrack'];
export type PlaylistCreationRequest = components['schemas']['PlaylistCreationRequest'];
export type PlaylistCreationResponse = components['schemas']['PlaylistCreationResponse'];
export type SpotifyMatch = components['schemas']['SpotifyMatch'];
export type SpotifyTrack = components['schemas']['SpotifyTrack'];
export type $defs = Record<string, never>;
export interface operations {
    ConfigureLastfm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigureLastfmRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigureLastfmResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    ConfigureDiscogs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigureDiscogsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigureDiscogsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    ConfigureSetlistFm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigureSetlistRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigureSetlistResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    MatchTracksToSpotify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchTracksRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchedDataResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    SearchSpotifyTracks: {
        parameters: {
            query?: {
                query?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpotifyTrack"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    CreatePlaylist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaylistCreationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistCreationResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    FetchLastfmData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FetchLastfmDataRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LastfmDataResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    FetchLastfmDataNormalized: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FetchLastfmDataRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NormalizedDataResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
